name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Get missing Modules 1
      run:  go get github.com/anmitsu/go-shlex 
    
    - name: Get missing Modules 2
      run:  go get -u golang.org/x/crypto/...
    
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
